//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class PoseListMsg : Message
    {
        public const string k_RosMessageName = "xarm_moveit/PoseList";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg[] pose_list;

        public PoseListMsg()
        {
            this.joints = new double[6];
            this.pose_list = new Geometry.PoseMsg[0];
        }

        public PoseListMsg(double[] joints, Geometry.PoseMsg[] pose_list)
        {
            this.joints = joints;
            this.pose_list = pose_list;
        }

        public static PoseListMsg Deserialize(MessageDeserializer deserializer) => new PoseListMsg(deserializer);

        private PoseListMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
            deserializer.Read(out this.pose_list, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.WriteLength(this.pose_list);
            serializer.Write(this.pose_list);
        }

        public override string ToString()
        {
            return "PoseListMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\npose_list: " + System.String.Join(", ", pose_list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
